### PR TITLE
add units for hvac and electric vehicle efficiency

### LINKED ISSUE #28: units for electric vehicle efficiency
include common units for electric vehicle efficiency. Use amount of electricity per distance and omit the inverses.

### LINKED ISSUE #29: add units for HVAC client
Units that are used by HVAC client that are not currently in the reference data:

pazrd:_UnitOfMeasure_american_wire_gauge
pazrd:_UnitOfMeasure_bag
pazrd:_UnitOfMeasure_box
pazrd:_UnitOfMeasure_british_thermal_unit_per_watt
pazrd:_UnitOfMeasure_canister
pazrd:_UnitOfMeasure_case
pazrd:_UnitOfMeasure_color_rendering_index
pazrd:_UnitOfMeasure_gauge
pazrd:_UnitOfMeasure_inch_of_water_gauge
pazrd:_UnitOfMeasure_mbh
pazrd:_UnitOfMeasure_ounce_per_foot
pazrd:_UnitOfMeasure_pack
pazrd:_UnitOfMeasure_pair
pazrd:_UnitOfMeasure_piece
pazrd:_UnitOfMeasure_pound
pazrd:_UnitOfMeasure_pound_per_inch
pazrd:_UnitOfMeasure_pound_per_square_inch_gauge
pazrd:_UnitOfMeasure_set
pazrd:_UnitOfMeasure_sheet
pazrd:_UnitOfMeasure_standard_cubic_foot
pazrd:_UnitOfMeasure_standard_cubic_foot_per_minute
pazrd:_UnitOfMeasure_ton
pazrd:_UnitOfMeasure_tube

gist:_UnitOfMeasure_british_thermal_unit  
gist:_UnitOfMeasure_british_thermal_unit_per_hour

Some things to resolve:
Apparently British Thermal Unit has variations:
 
     1 BTU Thermochemical = 1054.35 Joules 
     1 BTU International = 1055.06 Joules
 
Does the client use both? If the client unit does not specify which one they mean, does it always mean the same thing (and which one)?
 
Wire gauge will need to be inverse distance. I’m guessing it is not linear so there is no conversion factor.
 
Will need to think about how to handle canister, case, etc. because the number of items in a case will vary by context.
 
Inch of water gauge is another term for inch of water as a unit of pressure.
 
The client might be using pound two ways: pound of force (pressure) or pound of mass. In the reference data, “pound” is mass and “pound force” is force. They are two different things.
 
Standard cubic foot is an amount of matter (moles). For a given type of gas, it is the amount of gas that occupies a cubic foot at a given temperature and pressure. It depends on the type of gas. So it is a pseudo-unit.
 
What does the client mean by “set”?

### PR DESCRIPTION
**Pull request by philblackwood**
closes #29 
closes #28 

also added rdf-toolkit.jar to local repository so serializer is now running.

### CODE REVIEW

**Comment by philblackwood** [comment]
@rjyounes please take a look at the branch conflict ... not sure how to resolve it.

**Comment by rjyounes** [comment]
@philblackwood Apparently the jar file did get successfully added to this branch, so it was conflicting with the one from my PR. I've now resolved the conflict.

**Review by rjyounes — COMMENTED** [review]
@philblackwood I cannot make inline comments due to the file size. I happened to notice  a couple of issues in passing:

- The annotations of some of the btu units contain what appear to be non-ASCII characters. My text editor does not render them, so I'm not sure what they are, but you can see them starting at line 17528. 
- In at least one case (`gistd:_UnitOfMeasure_british_thermal_unit_international_inch_per_hour_square_foot_degree_fahrenheit`) there are duplicate altLabels, prefLabels, and scopeNotes, one with and one without the mysterious character.
- In units where you removed `table` and `definition` from the IRI, you have retained them in the labels - e.g., `gistd:_UnitOfMeasure_british_thermal_unit_international_inch_per_second_square_foot_degree_fahrenheit`. This may be intended, in which case it's fine; I thought I'd bring it to your attention in case it wasn't intentional.

There are one or two questions related to my HVAC client needs which I'll address in another comment.

**Comment by philblackwood** [comment]
@rjyounes  There are many non-ASCII characters from QUDT, such as symbol for degrees (Fahrenheit). Is there a general approach to dealing with these? 

Also, I cleaned up the duplicates ... and what look like some cases where maybe the serializer got confused (special characters?).

**Comment by MichaelSullivanArchitect** [comment]
FWIW, we have the requirement of supporting multiple unit symbol code styles. 
Here's what we did for our datatype properties:

- uom:value_UnitSymbol "m^2" ;
- uom:value_UnitSymbolHtml "m&sup2;" ;
- uom:value_UnitSymbolUnicode "U+0032" ;

**Pull request merged**
